name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  cd:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            path: ${{ github.event.repository.name }}

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.10.6

        - name: Install Poetry
          uses: snok/install-poetry@v1
          with:
            virtualenvs-in-project: true
            virtualenvs-path: ${{ github.event.repository.name }}

        - name: Load cached venv
          id: cached-poetry-dependencies
          uses: actions/cache@v3
          with:
              path: ${{ github.event.repository.name }}/.venv
              key: venv-${{ hashFiles('**/poetry.lock') }}

        - name: Install dependencies
          if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
          run: |
            cd ${{ github.event.repository.name }}
            poetry install --no-interaction --without dev

        - name: Pack CLI
          run: tar -cvf ${{ github.event.repository.name }}.tgz ${{ github.event.repository.name }}

        - name: Publish package
          uses: actions/upload-artifact@v3
          with:
            name: package
            path: ${{ github.event.repository.name }}.tgz
            retention-days: 30